### PR TITLE
change Node $id type to mixed instead of int (minor)

### PR DESCRIPTION
**Pull request by Mulkave**
Encountered this issue when using a string primary key (UUID):

```
exception: "TypeError"
file: "/var/www/html/vendor/laudis/neo4j-php-client/src/Types/Node.php"
line: 43
message: "Laudis\\Neo4j\\Types\\Node::__construct(): Argument #1 ($id) must be of type int, string given
```

### CODE REVIEW

**Comment by transistive** [comment]
Hello @Mulkave,

Thank you for your PR. This is a friendly reminder that the mixed keyword was only recently added in PHP 8, but the library also supports 7.4 so we can't use it yet (which is why the CI complains).

Also, the OGM is supposed to be a strict relationship with Neo4J objects, is there any example of non-int ids? In that case we can use mixed or string, otherwise I can take a look at NeoEloquent to get it to work with string IDs

**Comment by stefanak-michal** [comment]
I don't know PHP client details but Neo4j returns ID as integer.

https://neo4j.com/docs/cypher-manual/current/functions/scalar/#functions-id

**Comment by stefanak-michal** [comment]
Maybe one more link to see ID of Node is integer https://www.neo4j.com/docs/bolt/current/packstream/#structure-node

**Comment by transistive** [comment]
I'm going to close this issue due to inactivity. We will keep the ID as an integer as per documentation in pack stream.

**Pull request closed without merging**
