### PR TITLE
updated used versions

### PR DESCRIPTION
**Pull request by stefanak-michal**
Some versions are EOL and I'm curious how your tests will handle it

### CODE REVIEW

**Comment by transistive** [comment]
So am I :) Thanks Michal! I can check later today what went wrong on 5.1 test

**Comment by transistive** [comment]
Hi @stefanak-michal,

Thank you for your work! I have already merged it in the 3.0 branch. Expect a PR very soon!

Kind regards,

Ghlen

**Comment by stefanak-michal** [comment]
Yeah I just updated my fork and it executed these CI on yours repo ...weird 🍟

**Comment by transistive** [comment]
Superseded by https://github.com/neo4j-php/neo4j-php-client/pull/165

**Pull request closed without merging**
